### ISSUE TITLE
Add function to EmpireViewModel to reset all EmpireProperty[s] to their original value

### ISSUE THREAD

**Issue by jshep23** [strivesolutions/flutter_empire#72]
**Describe the solution you'd like**
Currently, there is a `reset` function on an `EmpireProperty` that will set the value to the original value it was given when initialized or the value set by calling `setOriginalValueToCurrent()`.

If you have many properties that you want to reset, you have to call the reset function on each property one by one, which is annoying. Should add a function to the EmpireViewModel called `resetAll`, that iterates over all the properties in the `empireProps` list, and calls reset on each EmpireProperty.

**Comment by Shubham1450** [comment]
I want to work on this issue.

**Comment by jshep23** [comment]
Sounds great @Shubham1450, thanks! It's all yours. Please check out the contributing section on the README.

**Comment by jshep23** [comment]
There hasn't been any movement here, and we would like to get this implemented asap. Going to take this one over and get it in today.
